### ISSUE TITLE
Create point clouds from label images

### ISSUE THREAD

**Issue by kapoorlab** [Sentinal4D/cellshape-helper#11]
**Is your feature request related to a problem? Please describe.**
Instead of inputting binary masks there can also be a functionality for inputting label images instead, this is useful in the case of overlapping/touching cells. 

**Describe the solution you'd like**
For each label in the label image iterate over the region, create a binary region and make a point cloud from it and then repeat for each label. Such code exists and we can just incorporate it in the code base of this repo.

**Describe alternatives you've considered**
Eroding the pixels before making the point clouds but that is only an approximate solution.

**Additional context**
None

**Comment by kapoorlab** [comment]
Just to be sure I understand this correctly, the directory containing binary masks should have only a single mask per file right? All the files should have the same patch size?

**Comment by DeVriesMatt** [comment]
Thank you for this request! I agree this is useful! 👍 

When each point cloud is created, it would be useful to centre it around the origin to avoid problems downstream.

To answer your questions:
- The directory of the binary masks currently only uses a single mask.
- The files don't necessarily have to have the same patch size.

**Comment by kapoorlab** [comment]
So I propose to do the following for this:

- Create a function that iterates over the labels in a label image, creates a patch that takes the centroid of the label and creates a 3D bounding box using skimage.regionprops. For that box it creates a PC and then saves a .ply files containing PC corresponding to that label. For the mesh, marching cubes on the binary image corresponding to that label.
This can then be opened using PointDataset class for training as usual.
